import os

GL_VERSION_1_0 = 0
GL_VERSION_1_1 = 1
GL_VERSION_1_2 = 2
GL_VERSION_1_3 = 3
GL_VERSION_1_4 = 4
GL_VERSION_1_5 = 5

GL_VERSION_2_0 = 6
GL_VERSION_2_1 = 7

GL_VERSION_3_0 = 8
GL_VERSION_3_1 = 9
GL_VERSION_3_2 = 10
GL_VERSION_3_3 = 11

GL_VERSION_4_0 = 12
GL_VERSION_4_1 = 13
GL_VERSION_4_2 = 14
GL_VERSION_4_3 = 15
GL_VERSION_4_4 = 16
GL_VERSION_4_5 = 17

GL_VERSION = {
    GL_VERSION_1_0 : 1.0,
    GL_VERSION_1_1 : 1.1,
    GL_VERSION_1_2 : 1.2,
    GL_VERSION_1_3 : 1.3,
    GL_VERSION_1_4 : 1.4,
    GL_VERSION_1_5 : 1.5,

    GL_VERSION_2_0 : 2.0,
    GL_VERSION_2_1 : 2.1,

    GL_VERSION_3_0 : 3.0,
    GL_VERSION_3_1 : 3.1,
    GL_VERSION_3_2 : 3.2,
    GL_VERSION_3_3 : 3.3,

    GL_VERSION_4_0 : 4.0,
    GL_VERSION_4_1 : 4.1,
    GL_VERSION_4_2 : 4.2,
    GL_VERSION_4_3 : 4.3,
    GL_VERSION_4_4 : 4.4,
    GL_VERSION_4_5 : 4.5,
}

GL_VERSION_MAJOR = {
    GL_VERSION_1_0 : 1,
    GL_VERSION_1_1 : 1,
    GL_VERSION_1_2 : 1,
    GL_VERSION_1_3 : 1,
    GL_VERSION_1_4 : 1,
    GL_VERSION_1_5 : 1,

    GL_VERSION_2_0 : 2,
    GL_VERSION_2_1 : 2,

    GL_VERSION_3_0 : 3,
    GL_VERSION_3_1 : 3,
    GL_VERSION_3_2 : 3,
    GL_VERSION_3_3 : 3,

    GL_VERSION_4_0 : 4,
    GL_VERSION_4_1 : 4,
    GL_VERSION_4_2 : 4,
    GL_VERSION_4_3 : 4,
    GL_VERSION_4_4 : 4,
    GL_VERSION_4_5 : 4,
}

GL_VERSION_MINOR = {
    GL_VERSION_1_0 : 0,
    GL_VERSION_1_1 : 1,
    GL_VERSION_1_2 : 2,
    GL_VERSION_1_3 : 3,
    GL_VERSION_1_4 : 4,
    GL_VERSION_1_5 : 5,

    GL_VERSION_2_0 : 0,
    GL_VERSION_2_1 : 1,

    GL_VERSION_3_0 : 0,
    GL_VERSION_3_1 : 1,
    GL_VERSION_3_2 : 2,
    GL_VERSION_3_3 : 3,

    GL_VERSION_4_0 : 0,
    GL_VERSION_4_1 : 1,
    GL_VERSION_4_2 : 2,
    GL_VERSION_4_3 : 3,
    GL_VERSION_4_4 : 4,
    GL_VERSION_4_5 : 5,
}

GL_CORE = {}
GL_EXTENSIONS = {}

def GL_CORE_PROC(version, func_type, func_name):
    if not version in GL_CORE:
        GL_CORE[version] = []

    GL_CORE[version].append((func_type, func_name))

def GL_EXT_PROC(ext, func_type, func_name)
	if not ext in GL_EXTENSIONS:
		GL_EXTENSIONS[ext] = []

	GL_EXTENSIONS[ext].append((func_type, func_name))


# OpenGL 1.0
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCULLFACEPROC", "glCullFace")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLFRONTFACEPROC", "glFrontFace")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLHINTPROC", "glHint")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLLINEWIDTHPROC", "glLineWidth")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLPOINTSIZEPROC", "glPointSize")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLPOLYGONMODEPROC", "glPolygonMode")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLSCISSORPROC", "glScissor")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXPARAMETERFPROC", "glTexParameterf")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXPARAMETERFVPROC", "glTexParameterfv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXPARAMETERIPROC", "glTexParameteri")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXPARAMETERIVPROC", "glTexParameteriv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXIMAGE1DPROC", "glTexImage1D")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLTEXIMAGE2DPROC", "glTexImage2D")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLDRAWBUFFERPROC", "glDrawBuffer")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCLEARPROC", "glClear")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCLEARCOLORPROC", "glClearColor")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCLEARSTENCILPROC", "glClearStencil")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCLEARDEPTHPROC", "glClearDepth")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLSTENCILMASKPROC", "glStencilMask")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLCOLORMASKPROC", "glColorMask")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLDEPTHMASKPROC", "glDepthMask")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLDISABLEPROC", "glDisable")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLENABLEPROC", "glEnable")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLFINISHPROC", "glFinish")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLFLUSHPROC", "glFlush")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLBLENDFUNCPROC", "glBlendFunc")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLLOGICOPPROC", "glLogicOp")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLSTENCILFUNCPROC", "glStencilFunc")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLSTENCILOPPROC", "glStencilOp")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLDEPTHFUNCPROC", "glDepthFunc")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLPIXELSTOREFPROC", "glPixelStoref")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLPIXELSTOREIPROC", "glPixelStorei")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLREADBUFFERPROC", "glReadBuffer")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLREADPIXELSPROC", "glReadPixels")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETBOOLEANVPROC", "glGetBooleanv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETDOUBLEVPROC", "glGetDoublev")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETERRORPROC", "glGetError")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETFLOATVPROC", "glGetFloatv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETINTEGERVPROC", "glGetIntegerv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETSTRINGPROC", "glGetString")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETTEXIMAGEPROC", "glGetTexImage")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETTEXPARAMETERFVPROC", "glGetTexParameterfv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETTEXPARAMETERIVPROC", "glGetTexParameteriv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETTEXLEVELPARAMETERFVPROC", "glGetTexLevelParameterfv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLGETTEXLEVELPARAMETERIVPROC", "glGetTexLevelParameteriv")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLISENABLEDPROC", "glIsEnabled")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLDEPTHRANGEPROC", "glDepthRange")
GL_CORE_PROC(GL_VERSION_1_0, "PFNGLVIEWPORTPROC", "glViewport")

# OpenGL 1.1
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLDRAWARRAYSPROC", "glDrawArrays")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLDRAWELEMENTSPROC", "glDrawElements")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLGETPOINTERVPROC", "glGetPointerv")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLPOLYGONOFFSETPROC", "glPolygonOffset")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLCOPYTEXIMAGE1DPROC", "glCopyTexImage1D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLCOPYTEXIMAGE2DPROC", "glCopyTexImage2D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLCOPYTEXSUBIMAGE1DPROC", "glCopyTexSubImage1D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLCOPYTEXSUBIMAGE2DPROC", "glCopyTexSubImage2D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLTEXSUBIMAGE1DPROC", "glTexSubImage1D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLTEXSUBIMAGE2DPROC", "glTexSubImage2D")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLBINDTEXTUREPROC", "glBindTexture")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLDELETETEXTURESPROC", "glDeleteTextures")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLGENTEXTURESPROC", "glGenTextures")
GL_CORE_PROC(GL_VERSION_1_1, "PFNGLISTEXTUREPROC", "glIsTexture")

# OpenGL 1.2
GL_CORE_PROC(GL_VERSION_1_2, "PFNGLDRAWRANGEELEMENTSPROC", "glDrawRangeElements")
GL_CORE_PROC(GL_VERSION_1_2, "PFNGLTEXIMAGE3DPROC", "glTexImage3D")
GL_CORE_PROC(GL_VERSION_1_2, "PFNGLTEXSUBIMAGE3DPROC", "glTexSubImage3D")
GL_CORE_PROC(GL_VERSION_1_2, "PFNGLCOPYTEXSUBIMAGE3DPROC", "glCopyTexSubImage3D")

# OpenGL 1.3
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLACTIVETEXTUREPROC", "glActiveTexture")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLSAMPLECOVERAGEPROC", "glSampleCoverage")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXIMAGE1DPROC", "glCompressedTexImage1D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXIMAGE2DPROC", "glCompressedTexImage2D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXIMAGE3DPROC", "glCompressedTexImage3D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC", "glCompressedTexSubImage1D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC", "glCompressedTexSubImage2D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC", "glCompressedTexSubImage3D")
GL_CORE_PROC(GL_VERSION_1_3, "PFNGLGETCOMPRESSEDTEXIMAGEPROC", "glGetCompressedTexImage")

# OpenGL 1.4
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLBLENDFUNCSEPARATEPROC", "glBlendFuncSeparate")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLMULTIDRAWARRAYSPROC", "glMultiDrawArrays")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLMULTIDRAWELEMENTSPROC", "glMultiDrawElements")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLPOINTPARAMETERFPROC", "glPointParameterf")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLPOINTPARAMETERFVPROC", "glPointParameterfv")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLPOINTPARAMETERIPROC", "glPointParameteri")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLPOINTPARAMETERIVPROC", "glPointParameteriv")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLBLENDCOLORPROC", "glBlendColor")
GL_CORE_PROC(GL_VERSION_1_4, "PFNGLBLENDEQUATIONPROC", "glBlendEquation")

# OpenGL 1.5
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGENQUERIESPROC", "glGenQueries")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLDELETEQUERIESPROC", "glDeleteQueries")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLISQUERYPROC", "glIsQuery")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLBEGINQUERYPROC", "glBeginQuery")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLENDQUERYPROC", "glEndQuery")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETQUERYIVPROC", "glGetQueryiv")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETQUERYOBJECTIVPROC", "glGetQueryObjectiv")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETQUERYOBJECTUIVPROC", "glGetQueryObjectuiv")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLBINDBUFFERPROC", "glBindBuffer")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLDELETEBUFFERSPROC", "glDeleteBuffers")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGENBUFFERSPROC", "glGenBuffers")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLISBUFFERPROC", "glIsBuffer")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLBUFFERDATAPROC", "glBufferData")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLBUFFERSUBDATAPROC", "glBufferSubData")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETBUFFERSUBDATAPROC", "glGetBufferSubData")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLMAPBUFFERPROC", "glMapBuffer")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLUNMAPBUFFERPROC", "glUnmapBuffer")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETBUFFERPARAMETERIVPROC", "glGetBufferParameteriv")
GL_CORE_PROC(GL_VERSION_1_5, "PFNGLGETBUFFERPOINTERVPROC", "glGetBufferPointerv")

# OpenGL 2.0
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLBLENDEQUATIONSEPARATEPROC", "glBlendEquationSeparate")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLDRAWBUFFERSPROC", "glDrawBuffers")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLSTENCILOPSEPARATEPROC", "glStencilOpSeparate")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLSTENCILFUNCSEPARATEPROC", "glStencilFuncSeparate")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLSTENCILMASKSEPARATEPROC", "glStencilMaskSeparate")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLATTACHSHADERPROC", "glAttachShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLBINDATTRIBLOCATIONPROC", "glBindAttribLocation")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLCOMPILESHADERPROC", "glCompileShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLCREATEPROGRAMPROC", "glCreateProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLCREATESHADERPROC", "glCreateShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLDELETEPROGRAMPROC", "glDeleteProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLDELETESHADERPROC", "glDeleteShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLDETACHSHADERPROC", "glDetachShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLDISABLEVERTEXATTRIBARRAYPROC", "glDisableVertexAttribArray")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLENABLEVERTEXATTRIBARRAYPROC", "glEnableVertexAttribArray")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETACTIVEATTRIBPROC", "glGetActiveAttrib")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETACTIVEUNIFORMPROC", "glGetActiveUniform")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETATTACHEDSHADERSPROC", "glGetAttachedShaders")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETATTRIBLOCATIONPROC", "glGetAttribLocation")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETPROGRAMIVPROC", "glGetProgramiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETPROGRAMINFOLOGPROC", "glGetProgramInfoLog")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETSHADERIVPROC", "glGetShaderiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETSHADERINFOLOGPROC", "glGetShaderInfoLog")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETSHADERSOURCEPROC", "glGetShaderSource")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETUNIFORMLOCATIONPROC", "glGetUniformLocation")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETUNIFORMFVPROC", "glGetUniformfv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETUNIFORMIVPROC", "glGetUniformiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETVERTEXATTRIBDVPROC", "glGetVertexAttribdv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETVERTEXATTRIBFVPROC", "glGetVertexAttribfv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETVERTEXATTRIBIVPROC", "glGetVertexAttribiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLGETVERTEXATTRIBPOINTERVPROC", "glGetVertexAttribPointerv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLISPROGRAMPROC", "glIsProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLISSHADERPROC", "glIsShader")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLLINKPROGRAMPROC", "glLinkProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLSHADERSOURCEPROC", "glShaderSource")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUSEPROGRAMPROC", "glUseProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM1FPROC", "glUniform1f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM2FPROC", "glUniform2f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM3FPROC", "glUniform3f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM4FPROC", "glUniform4f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM1IPROC", "glUniform1i")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM2IPROC", "glUniform2i")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM3IPROC", "glUniform3i")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM4IPROC", "glUniform4i")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM1FVPROC", "glUniform1fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM2FVPROC", "glUniform2fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM3FVPROC", "glUniform3fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM4FVPROC", "glUniform4fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM1IVPROC", "glUniform1iv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM2IVPROC", "glUniform2iv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM3IVPROC", "glUniform3iv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORM4IVPROC", "glUniform4iv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORMMATRIX2FVPROC", "glUniformMatrix2fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORMMATRIX3FVPROC", "glUniformMatrix3fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLUNIFORMMATRIX4FVPROC", "glUniformMatrix4fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVALIDATEPROGRAMPROC", "glValidateProgram")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1DPROC", "glVertexAttrib1d")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1DVPROC", "glVertexAttrib1dv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1FPROC", "glVertexAttrib1f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1FVPROC", "glVertexAttrib1fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1SPROC", "glVertexAttrib1s")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB1SVPROC", "glVertexAttrib1sv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2DPROC", "glVertexAttrib2d")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2DVPROC", "glVertexAttrib2dv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2FPROC", "glVertexAttrib2f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2FVPROC", "glVertexAttrib2fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2SPROC", "glVertexAttrib2s")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB2SVPROC", "glVertexAttrib2sv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3DPROC", "glVertexAttrib3d")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3DVPROC", "glVertexAttrib3dv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3FPROC", "glVertexAttrib3f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3FVPROC", "glVertexAttrib3fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3SPROC", "glVertexAttrib3s")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB3SVPROC", "glVertexATtrib3sv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NBVPROC", "glVertexAttrib4Nbv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NIVPROC", "glVertexAttrib4Niv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NSVPROC", "glVertexAttrib4Nsv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NUBPROC", "glVertexAttrib4Nub")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NUBVPROC", "glVertexAttrib4Nubv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NUIVPROC", "glVertexAttrib4Nuiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4NUSVPROC", "glVertexAttrib4Nusv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4BVPROC", "glVertexAttrib4bv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4DPROC", "glVertexAttrib4d")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4DVPROC", "glVertexAttrib4dv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4FPROC", "glVertexAttrib4f")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4FVPROC", "glVertexAttrib4fv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4IVPROC", "glVertexAttrib4iv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4SPROC", "glVertexAttrib4s")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4SVPROC", "glVertexAttrib4sv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4UBVPROC", "glVertexAttrib4ubv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4UIVPROC", "glVertexAttrib4uiv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIB4USVPROC", "glVertexAttrib4usv")
GL_CORE_PROC(GL_VERSION_2_0, "PFNGLVERTEXATTRIBPOINTERPROC", "glVertexAttribPointer")

# OpenGL 2.1
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX2X3FVPROC", "glUniformMatrix2x3fv")
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX3X2FVPROC", "glUniformMatrix3x2fv")
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX2X4FVPROC", "glUniformMatrix2x4fv")
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX4X2FVPROC", "glUniformMatrix4x2fv")
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX3X4FVPROC", "glUniformMatrix3x4fv")
GL_CORE_PROC(GL_VERSION_2_1, "PFNGLUNIFORMMATRIX4X3FVPROC", "glUniformMatrix4x3fv")

# OpenGL 3.0
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCOLORMASKIPROC", "glColorMaski")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETBOOLEANI_VPROC", "glGetBooleani_v")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETINTEGERI_VPROC", "glGetIntegeri_v")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLENABLEIPROC", "glEnablei")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLDISABLEIPROC", "glDisablei")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLISENABLEDIPROC", "glIsEnabledi")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBEGINTRANSFORMFEEDBACKPROC", "glBeginTransformFeedback")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLENDTRANSFORMFEEDBACKPROC", "glEndTransformFeedback")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDBUFFERRANGEPROC", "glBindBufferRange")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDBUFFERBASEPROC", "glBindBufferBase")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLTRANSFORMFEEDBACKVARYINGSPROC", "glTransformFeedbackVaryings")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETTRANSFORMFEEDBACKVARYINGPROC", "glGetTransformFeedbackVarying")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCLAMPCOLORPROC", "glClampColor")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBEGINCONDITIONALRENDERPROC", "glBeginConditionalRender")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLENDCONDITIONALRENDERPROC", "glEndConditionalRender")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBIPOINTERPROC", "glVertexAttribIPointer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETVERTEXATTRIBIIVPROC", "glGetVertexAttribIiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETVERTEXATTRIBIUIVPROC", "glGetVertexAttribIuiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI1IPROC", "glVertexAttribI1i")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI2IPROC", "glVertexAttribI2i")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI3IPROC", "glVertexAttribI3i")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4IPROC", "glVertexAttribI4i")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI1UIPROC", "glVertexAttribI1ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI2UIPROC", "glVertexAttribI2ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI3UIPROC", "glVertexAttribI3ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4UIPROC", "glVertexAttribI4ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI1IVPROC", "glVertexAttribI1iv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI2IVPROC", "glVertexAttribI2iv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI3IVPROC", "glVertexAttribI3iv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4IVPROC", "glVertexAttribI4iv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI1UIVPROC", "glVertexAttribI1uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI2UIVPROC", "glVertexAttribI2uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI3UIVPROC", "glVertexAttribI3uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4UIVPROC", "glVertexAttribI4uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4BVPROC", "glVertexAttribI4bv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4SVPROC", "glVertexAttribI4sv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4UBVPROC", "glVertexAttribI4ubv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLVERTEXATTRIBI4USVPROC", "glVertexAttribI4usv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETUNIFORMUIVPROC", "glGetUniformuiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDFRAGDATALOCATIONPROC", "glBindFragDataLocation")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETFRAGDATALOCATIONPROC", "glGetFragDataLocation")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM1UIPROC", "glUniform1ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM2UIPROC", "glUniform2ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM3UIPROC", "glUniform3ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM4UIPROC", "glUniform4ui")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM1UIVPROC", "glUniform1uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM2UIVPROC", "glUniform2uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM3UIVPROC", "glUniform3uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLUNIFORM4UIVPROC", "glUniform4uiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLTEXPARAMETERIIVPROC", "glTexParameterIiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLTEXPARAMETERIUIVPROC", "glTexParameterIuiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETTEXPARAMETERIIVPROC", "glGetTexParameterIiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETTEXPARAMETERIUIVPROC", "glGetTexParameterIuiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCLEARBUFFERIVPROC", "glClearBufferiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCLEARBUFFERUIVPROC", "glClearBufferuiv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCLEARBUFFERFVPROC", "glClearBufferfv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCLEARBUFFERFIPROC", "glClearBufferfi")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETSTRINGIPROC", "glGetStringi")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLISRENDERBUFFERPROC", "glIsRenderbuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDRENDERBUFFERPROC", "glBindRenderbuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLDELETERENDERBUFFERSPROC", "glDeleteRenderbuffers")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGENRENDERBUFFERSPROC", "glGenRenderbuffers")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLRENDERBUFFERSTORAGEPROC", "glRenderbufferStorage")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETRENDERBUFFERPARAMETERIVPROC", "glGetRenderbufferParameteriv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLISFRAMEBUFFERPROC", "glIsFramebuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDFRAMEBUFFERPROC", "glBindFramebuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLDELETEFRAMEBUFFERSPROC", "glDeleteFramebuffers")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGENFRAMEBUFFERSPROC", "glGenFramebuffers")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLCHECKFRAMEBUFFERSTATUSPROC", "glCheckFramebufferStatus")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFRAMEBUFFERTEXTURE1DPROC", "glFramebufferTexture1D")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFRAMEBUFFERTEXTURE2DPROC", "glFramebufferTexture2D")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFRAMEBUFFERTEXTURE3DPROC", "glFramebufferTexture3D")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFRAMEBUFFERRENDERBUFFERPROC", "glFramebufferRenderbuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC", "glGetFramebufferAttachmentParameteriv")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGENERATEMIPMAPPROC", "glGenerateMipmap")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBLITFRAMEBUFFERPROC", "glBlitFramebuffer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC", "glRenderbufferStorageMultisample")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFRAMEBUFFERTEXTURELAYERPROC", "glFramebufferTextureLayer")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLMAPBUFFERRANGEPROC", "glMapBufferRange")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLFLUSHMAPPEDBUFFERRANGEPROC", "glFlushMappedBufferRange")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLBINDVERTEXARRAYPROC", "glBindVertexArray")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLDELETEVERTEXARRAYSPROC", "glDeleteVertexArrays")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLGENVERTEXARRAYSPROC", "glGenVertexArrays")
GL_CORE_PROC(GL_VERSION_3_0, "PFNGLISVERTEXARRAYPROC", "glIsVertexArray")

# OpenGL 3.1
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLDRAWARRAYSINSTANCEDPROC", "glDrawArraysInstanced")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLDRAWELEMENTSINSTANCEDPROC", "glDrawElementsInstanced")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLTEXBUFFERPROC", "glTexBuffer")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLPRIMITIVERESTARTINDEXPROC", "glPrimitiveRestartIndex")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLCOPYBUFFERSUBDATAPROC", "glCopyBufferSubData")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETUNIFORMINDICESPROC", "glGetUniformIndices")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETACTIVEUNIFORMSIVPROC", "glGetActiveUniformsiv")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETACTIVEUNIFORMNAMEPROC", "glGetActiveUniformName")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETUNIFORMBLOCKINDEXPROC", "glGetUniformBlockIndex")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETACTIVEUNIFORMBLOCKIVPROC", "glGetActiveUniformBlockiv")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC", "glGetActiveUniformBlockName")
GL_CORE_PROC(GL_VERSION_3_1, "PFNGLUNIFORMBLOCKBINDINGPROC", "glUniformBlockBinding")

# OpenGL 3.2
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLDRAWELEMENTSBASEVERTEXPROC", "glDrawElementsBaseVertex")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC", "glDrawRangeElementsBaseVertex")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC", "glDrawElementsInstancedBaseVertex")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC", "glMultiDrawElementsBaseVertex")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLPROVOKINGVERTEXPROC", "glProvokingVertex")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLFENCESYNCPROC", "glFenceSync")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLISSYNCPROC", "glIsSync")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLDELETESYNCPROC", "glDeleteSync")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLCLIENTWAITSYNCPROC", "glClientWaitSync")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLWAITSYNCPROC", "glWaitSync")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLGETINTEGER64VPROC", "glGetInteger64v")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLGETSYNCIVPROC", "glGetSynciv")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLGETINTEGER64I_VPROC", "glGetInteger64i_v")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLGETBUFFERPARAMETERI64VPROC", "glGetBufferParameteri64v")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLFRAMEBUFFERTEXTUREPROC", "glFramebufferTexture")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLTEXIMAGE2DMULTISAMPLEPROC", "glTexImage2DMultisample")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLTEXIMAGE3DMULTISAMPLEPROC", "glTexImage3DMultisample")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLGETMULTISAMPLEFVPROC", "glGetMultisamplefv")
GL_CORE_PROC(GL_VERSION_3_2, "PFNGLSAMPLEMASKIPROC", "glSampleMaski")

# OpenGL 3.3
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLBINDFRAGDATALOCATIONINDEXEDPROC", "glBindFragDataLocationIndexed")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETFRAGDATAINDEXPROC", "glGetFragDataIndex")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGENSAMPLERSPROC", "glGenSamplers")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLDELETESAMPLERSPROC", "glDeleteSamplers")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLISSAMPLERPROC", "glIsSampler")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLBINDSAMPLERPROC", "glBindSampler")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERIPROC", "glSamplerParameteri")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERIVPROC", "glSamplerParameteriv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERFPROC", "glSamplerParameterf")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERFVPROC", "glSamplerParameterfv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERIIVPROC", "glSamplerParameterIiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLSAMPLERPARAMETERIUIVPROC", "glSamplerParameterIuiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETSAMPLERPARAMETERIVPROC", "glGetSamplerParameteriv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETSAMPLERPARAMETERIIVPROC", "glGetSamplerParameterIiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETSAMPLERPARAMETERFVPROC", "glGetSamplerParameterfv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETSAMPLERPARAMETERIUIVPROC", "glGetSamplerParameterIuiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLQUERYCOUNTERPROC", "glQueryCounter")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETQUERYOBJECTI64VPROC", "glGetQueryObjecti64v")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLGETQUERYOBJECTUI64VPROC", "glGetQueryObjectui64v")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBDIVISORPROC", "glVertexAttribDivisor")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP1UIPROC", "glVertexAttribP1ui")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP1UIVPROC", "glVertexAttribP1uiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP2UIPROC", "glVertexAttribP2ui")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP2UIVPROC", "glVertexAttribP2uiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP3UIPROC", "glVertexAttribP3ui")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP3UIVPROC", "glVertexAttribP3uiv")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP4UIPROC", "glVertexAttribP4ui")
GL_CORE_PROC(GL_VERSION_3_3, "PFNGLVERTEXATTRIBP4UIVPROC", "glVertexAttribP4uiv")

# OpenGL 4.0
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLMINSAMPLESHADINGPROC", "glMinSampleShading")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBLENDEQUATIONIPROC", "glBlendEquationi")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBLENDEQUATIONSEPARATEIPROC", "glBlendEquationSeparatei")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBLENDFUNCIPROC", "glBlendFunci")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBLENDFUNCSEPARATEIPROC", "glBlendFuncSeparatei")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLDRAWARRAYSINDIRECTPROC", "glDrawArraysIndirect")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLDRAWELEMENTSINDIRECTPROC", "glDrawElementsIndirect")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM1DPROC", "glUniform1d")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM2DPROC", "glUniform2d")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM3DPROC", "glUniform3d")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM4DPROC", "glUniform4d")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM1DVPROC", "glUniform1dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM2DVPROC", "glUniform2dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM3DVPROC", "glUniform3dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORM4DVPROC", "glUniform4dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX2DVPROC", "glUniformMatrix2dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX3DVPROC", "glUniformMatrix3dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX4DVPROC", "glUniformMatrix4dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX2X3DVPROC", "glUniformMatrix2x3dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX2X4DVPROC", "glUniformMatrix2x4dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX3X2DVPROC", "glUniformMatrix3x2dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX3X4DVPROC", "glUniformMatrix3x4dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX4X2DVPROC", "glUniformMatrix4x2dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMMATRIX4X3DVPROC", "glUniformMatrix4x3dv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETUNIFORMDVPROC", "glGetUniformdv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC", "glGetSubroutineUniformLocation")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETSUBROUTINEINDEXPROC", "glGetSubroutineIndex")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC", "glGetActiveSubroutineUniformiv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC", "glGetActiveSubroutineUniformName")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETACTIVESUBROUTINENAMEPROC", "glGetActiveSubroutineName")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLUNIFORMSUBROUTINESUIVPROC", "glUniformSubroutinesuiv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETUNIFORMSUBROUTINEUIVPROC", "glGetUniformSubroutineuiv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETPROGRAMSTAGEIVPROC", "glGetProgramStageiv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLPATCHPARAMETERIPROC", "glPatchParameteri")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLPATCHPARAMETERFVPROC", "glPatchParameterfv")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBINDTRANSFORMFEEDBACKPROC", "glBindTransformFeedback")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLDELETETRANSFORMFEEDBACKSPROC", "glDeleteTransformFeedbacks")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGENTRANSFORMFEEDBACKSPROC", "glGenTransformFeedbacks")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLISTRANSFORMFEEDBACKPROC", "glIsTransformFeedback")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLPAUSETRANSFORMFEEDBACKPROC", "glPauseTransformFeedback")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLRESUMETRANSFORMFEEDBACKPROC", "glResumeTransformFeedback")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLDRAWTRANSFORMFEEDBACKPROC", "glDrawTransformFeedback")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC", "glDrawTransformFeedbackStream")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLBEGINQUERYINDEXEDPROC", "glBeginQueryIndexed")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLENDQUERYINDEXEDPROC", "glEndQueryIndexed")
GL_CORE_PROC(GL_VERSION_4_0, "PFNGLGETQUERYINDEXEDIVPROC", "glGetQueryIndexediv")

# OpenGL 4.1
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLRELEASESHADERCOMPILERPROC", "glReleaseShaderCompiler")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLSHADERBINARYPROC", "glShaderBinary")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETSHADERPRECISIONFORMATPROC", "glGetShaderPrecisionFormat")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLDEPTHRANGEFPROC", "glDepthRangef")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLCLEARDEPTHFPROC", "glClearDepthf")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETPROGRAMBINARYPROC", "glGetProgramBinary")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMBINARYPROC", "glProgramBinary")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMPARAMETERIPROC", "glProgramParameteri")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLUSEPROGRAMSTAGESPROC", "glUseProgramStages")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLACTIVESHADERPROGRAMPROC", "glActiveShaderProgram")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLCREATESHADERPROGRAMVPROC", "glCreateShaderProgramv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLBINDPROGRAMPIPELINEPROC", "glBindProgramPipeline")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLDELETEPROGRAMPIPELINESPROC", "glDeleteProgramPipelines")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGENPROGRAMPIPELINESPROC", "glGenProgramPipelines")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLISPROGRAMPIPELINEPROC", "glIsProgramPipeline")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETPROGRAMPIPELINEIVPROC", "glGetProgramPipelineiv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1IPROC", "glProgramUniform1i")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1IVPROC", "glProgramUniform1iv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1FPROC", "glProgramUniform1f")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1FVPROC", "glProgramUniform1fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1DPROC", "glProgramUniform1d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1DVPROC", "glProgramUniform1dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1UIPROC", "glProgramUniform1ui")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM1UIVPROC", "glProgramUniform1uiv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2IPROC", "glProgramUniform2i")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2IVPROC", "glProgramUniform2iv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2FPROC", "glProgramUniform2f")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2FVPROC", "glProgramUniform2fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2DPROC", "glProgramUniform2d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2DVPROC", "glProgramUniform2dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2UIPROC", "glProgramUniform2ui")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM2UIVPROC", "glProgramUniform2uiv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3IPROC", "glProgramUniform3i")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3IVPROC", "glProgramUniform3iv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3FPROC", "glProgramUniform3f")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3FVPROC", "glProgramUniform3fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3DPROC", "glProgramUniform3d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3DVPROC", "glProgramUniform3dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3UIPROC", "glProgramUniform3ui")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM3UIVPROC", "glProgramUniform3uiv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4IPROC", "glProgramUniform4i")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4IVPROC", "glProgramUniform4iv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4FPROC", "glProgramUniform4f")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4FVPROC", "glProgramUniform4fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4DPROC", "glProgramUniform4d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4DVPROC", "glProgramUniform4dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4UIPROC", "glProgramUniform4ui")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORM4UIVPROC", "glProgramUniform4uiv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2FVPROC", "glProgramUniformMatrix2fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3FVPROC", "glProgramUniformMatrix3fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4FVPROC", "glProgramUniformMatrix4fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2DVPROC", "glProgramUniformMatrix2dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3DVPROC", "glProgramUniformMatrix3dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4DVPROC", "glProgramUniformMatrix4dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC", "glProgramUniformMatrix2x3fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC", "glProgramUniformMatrix3x2fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC", "glProgramUniformMatrix2x4fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC", "glProgramUniformMatrix4x2fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC", "glProgramUniformMatrix3x4fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC", "glProgramUniformMatrix4x3fv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC", "glProgramUniformMatrix2x3dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC", "glProgramUniformMatrix3x2dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC", "glProgramUniformMatrix2x4dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC", "glProgramUniformMatrix4x2dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC", "glProgramUniformMatrix3x4dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC", "glProgramUniformMatrix4x3dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVALIDATEPROGRAMPIPELINEPROC", "glValidateProgramPipeline")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETPROGRAMPIPELINEINFOLOGPROC", "glGetProgramPipelineInfoLog")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL1DPROC", "glVertexAttribL1d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL2DPROC", "glVertexAttribL2d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL3DPROC", "glVertexAttribL3d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL4DPROC", "glVertexAttribL4d")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL1DVPROC", "glVertexAttribL1dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL2DVPROC", "glVertexAttribL2dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL3DVPROC", "glVertexAttribL3dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBL4DVPROC", "glVertexAttribL4dv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVERTEXATTRIBLPOINTERPROC", "glVertexAttribLPointer")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETVERTEXATTRIBLDVPROC", "glGetVertexAttribLdv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVIEWPORTARRAYVPROC", "glViewportArrayv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVIEWPORTINDEXEDFPROC", "glViewportIndexedf")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLVIEWPORTINDEXEDFVPROC", "glViewportIndexedfv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLSCISSORARRAYVPROC", "glScissorArrayv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLSCISSORINDEXEDPROC", "glScissorIndexed")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLSCISSORINDEXEDVPROC", "glScissorIndexedv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLDEPTHRANGEARRAYVPROC", "glDepthRangeArrayv")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLDEPTHRANGEINDEXEDPROC", "glDepthRangeIndexed")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETFLOATI_VPROC", "glGetFloati_v")
GL_CORE_PROC(GL_VERSION_4_1, "PFNGLGETDOUBLEI_VPROC", "glGetDoublei_v")

# OpenGL 4.2
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC", "glDrawArraysInstancedBaseInstance")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC", "glDrawElementsInstancedBaseInstance")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC", "glDrawElementsInstancedBaseVertexBaseInstance")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLGETINTERNALFORMATIVPROC", "glGetInternalformativ")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC", "glGetActiveAtomicCounterBufferiv")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLBINDIMAGETEXTUREPROC", "glBindImageTexture")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLMEMORYBARRIERPROC", "glMemoryBarrier")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLTEXSTORAGE1DPROC", "glTexStorage1D")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLTEXSTORAGE2DPROC", "glTexStorage2D")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLTEXSTORAGE3DPROC", "glTexStorage3D")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC", "glDrawTransformFeedbackInstanced")
GL_CORE_PROC(GL_VERSION_4_2, "PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC", "glDrawTransformFeedbackStreamInstanced")

# OpenGL 4.3
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLCLEARBUFFERDATAPROC", "glClearBufferData")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLCLEARBUFFERSUBDATAPROC", "glClearBufferSubData")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLDISPATCHCOMPUTEPROC", "glDispatchCompute")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLDISPATCHCOMPUTEINDIRECTPROC", "glDispatchComputeIndirect")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLCOPYIMAGESUBDATAPROC", "glCopyImageSubData")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLFRAMEBUFFERPARAMETERIPROC", "glFramebufferParameteri")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETFRAMEBUFFERPARAMETERIVPROC", "glGetFramebufferParameteriv")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETINTERNALFORMATI64VPROC", "glGetInternalFormati64v")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATETEXSUBIMAGEPROC", "glInvalidateTexSubImage")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATETEXIMAGEPROC", "glInvalidateTexImage")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATEBUFFERSUBDATAPROC", "glInvalidateBufferSubData")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATEBUFFERDATAPROC", "glInvalidateBufferData")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATEFRAMEBUFFERPROC", "glInvalidateFramebuffer")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLINVALIDATESUBFRAMEBUFFERPROC", "glInvalidateSubFramebuffer")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLMULTIDRAWARRAYSINDIRECTPROC", "glMultiDrawArraysIndirect")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLMULTIDRAWELEMENTSINDIRECTPROC", "glMultiDrawElementsIndirect")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMINTERFACEIVPROC", "glGetProgramInterfaceiv")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMRESOURCEINDEXPROC", "glGetProgramResourceIndex")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMRESOURCENAMEPROC", "glGetProgramResourceName")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMRESOURCEIVPROC", "glGetProgramResourceiv")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMRESOURCELOCATIONPROC", "glGetProgramResourceLocation")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC", "glGetProgramResourceLocationIndex")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLSHADERSTORAGEBLOCKBINDINGPROC", "glShaderStorageBlockBinding")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLTEXBUFFERRANGEPROC", "glTexBufferRange")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLTEXSTORAGE2DMULTISAMPLEPROC", "glTexStorage2DMultiSample")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLTEXSTORAGE3DMULTISAMPLEPROC", "glTexStorage2DMultisample")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLTEXTUREVIEWPROC", "glTextureView")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLBINDVERTEXBUFFERPROC", "glBindVertexBuffer")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLVERTEXATTRIBFORMATPROC", "glVertexAttribFormat")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLVERTEXATTRIBIFORMATPROC", "glVertexAttribIFormat")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLVERTEXATTRIBLFORMATPROC", "glVertexAttribLFormat")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLVERTEXATTRIBBINDINGPROC", "glVertexAttribBinding")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLVERTEXBINDINGDIVISORPROC", "glVertexBindingDivisor")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLDEBUGMESSAGECONTROLPROC", "glDebugMessageControl")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLDEBUGMESSAGEINSERTPROC", "glDebugMessageInsert")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLDEBUGMESSAGECALLBACKPROC", "glDebugMessageCallback")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETDEBUGMESSAGELOGPROC", "glGetDebugMessageLog")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLPUSHDEBUGGROUPPROC", "glPushDebugGroup")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLPOPDEBUGGROUPPROC", "glPopDebugGroup")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLOBJECTLABELPROC", "glObjectLabel")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETOBJECTLABELPROC", "glGetObjectLabel")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLOBJECTPTRLABELPROC", "glObjectPtrLabel")
GL_CORE_PROC(GL_VERSION_4_3, "PFNGLGETOBJECTPTRLABELPROC", "glGetObjectPtrLabel")

# OpenGL 4.4
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBUFFERSTORAGEPROC", "glBufferStorage")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLCLEARTEXIMAGEPROC", "glClearTexImage")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLCLEARTEXSUBIMAGEPROC", "glClearTexSubImage")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDBUFFERSBASEPROC", "glBindBuffersBase")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDBUFFERSRANGEPROC", "glBindBuffersRange")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDTEXTURESPROC", "glBindTextures")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDSAMPLERSPROC", "glBindSamplers")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDIMAGETEXTURESPROC", "glBindImageTextures")
GL_CORE_PROC(GL_VERSION_4_4, "PFNGLBINDVERTEXBUFFERSPROC", "glBindVertexBuffers")

# OpenGL 4.5
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLIPCONTROLPROC", "glClipControl")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATETRANSFORMFEEDBACKSPROC", "glCreateTransformFeedbacks")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC", "glTransformFeedbackBufferBase")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC", "glTransformFeedbackBufferRange")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTRANSFORMFEEDBACKIVPROC", "glGetTransformFeedbackiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTRANSFORMFEEDBACKI_VPROC", "glGetTransformFeedbacki_v")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTRANSFORMFEEDBACKI64_VPROC", "glGetTransformFeedbacki64_v")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATEBUFFERSPROC", "glCreateBuffers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDBUFFERSTORAGEPROC", "glNamedBufferStorage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDBUFFERDATAPROC", "glNamedBufferData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDBUFFERSUBDATAPROC", "glNameBufferSubData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOPYNAMEDBUFFERSUBDATAPROC", "glCopyNamedBufferSubData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDBUFFERDATAPROC", "glClearNamedBufferData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDBUFFERSUBDATAPROC", "glClearNamedBufferSubData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLMAPNAMEDBUFFERPROC", "glMapNamedBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLMAPNAMEDBUFFERRANGEPROC", "glMapNamedBufferRange")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLUNMAPNAMEDBUFFERPROC", "glUnmapNamedBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC", "glFlushMappedNamedBufferRange")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDBUFFERPARAMETERIVPROC", "glGetNamedBufferParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDBUFFERPARAMETERI64VPROC", "glGetNamedBufferParameteri64v")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDBUFFERPOINTERVPROC", "glGetNamedBufferPointerv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDBUFFERSUBDATAPROC", "glGetNamedBufferSubData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATEFRAMEBUFFERSPROC", "glCreateFramebuffers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC", "glNamedFramebufferRenderbuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC", "glNamedFramebufferParameteri")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERTEXTUREPROC", "glNamedFramebufferTexture")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC", "glNamedFramebufferTextureLayer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC", "glNamedFramebufferDrawBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC", "glNamedFramebufferDrawBuffers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC", "glNamedFramebufferReadBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC", "glInvalidateNamedFramebufferData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC", "glInvalidateNamedFramebufferSubData")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDFRAMEBUFFERIVPROC", "glClearNamedFramebufferiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC", "glClearNamedFramebufferuiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDFRAMEBUFFERFVPROC", "glClearNamedFramebufferfv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCLEARNAMEDFRAMEBUFFERFIPROC", "glClearNamedFramebufferfi")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLBLITNAMEDFRAMEBUFFERPROC", "glBlitNamedFramebuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC", "glCheckNamedFramebufferStatus")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC", "glGetNamedFramebufferParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC", "glGetNamedFramebufferAttachmentParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATERENDERBUFFERSPROC", "glCreateRenderbuffers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDRENDERBUFFERSTORAGEPROC", "glNamedRenderbufferStorage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC", "glNamedRenderbufferStorageMultisample")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC", "glGetNamedRenderbufferParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATETEXTURESPROC", "glCreateTextures")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREBUFFERPROC", "glTextureBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREBUFFERRANGEPROC", "glTextureBufferRange")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESTORAGE1DPROC", "glTextureStorage1D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESTORAGE2DPROC", "glTextureStorage2D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESTORAGE3DPROC", "glTextureStorage3D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC", "glTextureStorage2DMultisample")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC", "glTextureStorage3DMultisample")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESUBIMAGE1DPROC", "glTextureSubImage1D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESUBIMAGE2DPROC", "glTextureSubImage2D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTURESUBIMAGE3DPROC", "glTextureSubImage3D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC", "glCompressedTextureSubImage1D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC", "glCompressedTextureSubImage2D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC", "glCompressedTextureSubImage3D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOPYTEXTURESUBIMAGE1DPROC", "glCopyTextureSubImage1D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOPYTEXTURESUBIMAGE2DPROC", "glCopyTextureSubImage2D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCOPYTEXTURESUBIMAGE3DPROC", "glCopyTextureSubImage3D")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERFPROC", "glTextureParameterf")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERFVPROC", "glTextureParameterfv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERIPROC", "glTextureParameteri")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERIIVPROC", "glTextureParameterIiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERIUIVPROC", "glTextureParameterIuiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREPARAMETERIVPROC", "glTextureParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGENERATETEXTUREMIPMAPPROC", "glGenerateTextureMipmap")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLBINDTEXTUREUNITPROC", "glBindTextureUnit")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTUREIMAGEPROC", "glGetTextureImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC", "glGetCompressedTextureImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTURELEVELPARAMETERFVPROC", "glGetTextureLevelParameterfv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTURELEVELPARAMETERIVPROC", "glGetTextureLevelParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTUREPARAMETERFVPROC", "glGetTextureParameterfv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTUREPARAMETERIIVPROC", "glGetTextureParameterIiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTUREPARAMETERIUIVPROC", "glGetTextureParameterIuiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTUREPARAMETERIVPROC", "glGetTextureParameteriv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATEVERTEXARRAYSPROC", "glCreateVertexArrays")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLDISABLEVERTEXARRAYATTRIBPROC", "glDisableVertexArrayAttrib")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLENABLEVERTEXARRAYATTRIBPROC", "glEnableVertexArrayAttrib")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYELEMENTBUFFERPROC", "glVertexArrayElementBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYVERTEXBUFFERPROC", "glVertexArrayVertexBuffer")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYVERTEXBUFFERSPROC", "glVertexArrayVertexBuffers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYATTRIBBINDINGPROC", "glVertexArrayAttribBinding")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYATTRIBFORMATPROC", "glVertexArrayAttribFormat")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYATTRIBIFORMATPROC", "glVertexArrayAttribIFormat")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYATTRIBLFORMATPROC", "glVertexarrayAttribLFormat")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLVERTEXARRAYBINDINGDIVISORPROC", "glVertexArrayBindingDivisor")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETVERTEXARRAYIVPROC", "glGetVertexArrayiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETVERTEXARRAYINDEXEDIVPROC", "glGetVertexArrayIndexediv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETVERTEXARRAYINDEXED64IVPROC", "glGetVertexArrayIndexed64iv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATESAMPLERSPROC", "glCreateSamplers")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATEPROGRAMPIPELINESPROC", "glCreateProgramPipelines")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLCREATEQUERIESPROC", "glCreateQueries")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETQUERYBUFFEROBJECTI64VPROC", "glGetQueryBufferObjecti64v")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETQUERYBUFFEROBJECTIVPROC", "glGetQueryBufferObjectiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETQUERYBUFFEROBJECTUI64VPROC", "glGetQueryBufferObjectui64v")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETQUERYBUFFEROBJECTUIVPROC", "glGetQueryBufferObjectuiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLMEMORYBARRIERBYREGIONPROC", "glMemoryBarrierByRegion")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETTEXTURESUBIMAGEPROC", "glGetTextureSubImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC", "glGetCompressedTextureSubImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETGRAPHICSRESETSTATUSPROC", "glGetGraphicsResetStatus")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNCOMPRESSEDTEXIMAGEPROC", "glGetnCompressedTexImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNTEXIMAGEPROC", "glGetnTexImage")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNUNIFORMDVPROC", "glGetnUniformdv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNUNIFORMFVPROC", "glGetnUniformfv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETNUNIFORMIVPROC", "glGetnUniformiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLGETUNIFORMUIVPROC", "glGetnUniformuiv")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLREADNPIXELSPROC", "glReadnPixels")
GL_CORE_PROC(GL_VERSION_4_5, "PFNGLTEXTUREBARRIERPROC", "glTextureBarrier")



GL_CORE_SORTED = sorted(GL_CORE.items())

if not os.path.exists('gl'):
    os.makedirs('gl')

"""
// TODO: review extensions to be used for the low end OpenGL renderer
// and also which ones to use with the high end OpenGL renderer

// [low] extensions
// ARB_framebuffer_object / EXT_framebuffer_object
// ARB_uniform_buffer_object
// EXT_texture_array
// ARB_sync
// ARB_texture_storage
// ARB_vertex_attrib_binding
// ARB_explicit_attrib_location
// ARB_explicit_uniform_location
// ARB_shading_language_420pack
// ARB_debug_output

// [high] extensions
// ARB_shader_draw_parameters
// ARB_bindless_texture
"""

# generate gl_loader.h
with open("gl/gl_loader.h", "wb") as f:
    f.write(br'''// this file has been automatically generated by gllgen

#ifndef __GL_LOADER_H__
#define __GL_LOADER_H__

#include "glcorearb.h"
#include "glext.h"

#ifdef _WIN32
	#include "wglext.h"
#else
	#include "glxext.h"
#endif

// Loader API
// ==========
GLboolean	GL_LoadAPI();
void		GL_ReleaseAPI();

// Function Pointers
// =================

''')

    for version, proc_list in GL_CORE_SORTED:
        f.write(("\n// OpenGL %.1f\n" % GL_VERSION.get(version, 0)).encode("utf-8"))
        for proc_type, proc_name in proc_list:
            f.write(("GLAPI %s %s;\n" % (proc_type, proc_name)).encode("utf-8"))

    f.write(b"\n#endif //__GL_LOADER_H__\n")


# generate gl_loader.c
with open("gl/gl_loader.c", "wb") as f:
	f.write(br'''// this file has been automatically generated by gllgen

#include "gl_loader.h"

// to activate logging, a LOG_ERROR macro should
// be defined using any logging interface

#ifndef LOG_ERROR
    #define LOG_ERROR(fmt, ...)
#endif

#define GL_MAX_EXTENSION_COUNT 1024
#define GL_MAX_EXTENSION_STRING_LEN (GL_MAX_EXTENSION_COUNT * 32)

static GLboolean		l_loaded = GL_FALSE;
static GLuint			l_extensionCount;
static char				l_extensionString[GL_MAX_EXTENSION_STRING_LEN];
static const char		*l_pExtensions[GL_MAX_EXTENSION_COUNT];
''')

	for version, proc_list in GL_CORE_SORTED:
		f.write(("\n// OpenGL %.1f\n" % GL_VERSION.get(version, 0)).encode("utf-8"))
		for proc_type, proc_name in proc_list:
			f.write(("%s %s = NULL;\n" % (proc_type, proc_name)).encode("utf-8"))

	f.write(br'''
typedef (*PFNGLVOIDFUNCTION)(void);

#if defined(_WIN32)
static HMODULE l_libgl = NULL;
static GLboolean GL_OpenLib()
{
	if(l_libgl != NULL)
		return GL_TRUE;

	l_libgl = LoadLibraryA("opengl32.dll");
	return (l_libgl != NULL);
}
static void GL_CloseLib()
{
	if(l_libgl != NULL){
		FreeLibrary(l_libgl)
		l_libgl = NULL;
	}
}
static PFNGLVOIDFUNCTION GL_GetProcAddr(const char *procName)
{
	PFNGLVOIDFUNCTION proc;

	if(l_libgl == NULL)
		return NULL;

	proc = (PFNGLVOIDFUNCTION) wglGetProcAddress((LPCSTR)procName);
	if(proc == NULL)
		proc = (PFNGLVOIDFUNCTION) GetProcAddress(l_libgl, (LPCSTR)procName);

	return proc;
}
#endif

GLboolean GL_LoadAPI()
{
	const char *version, *ptr, *start;
	uint32_t major, minor;
	uint32_t res, i;

	PFNGLGETSTRINGPROC glGetStringLocal;
	PFNGLGETSTRINGIPROC glGetStringiLocal;
	PFNGLGETINTEGERVPROC glGetIntegervLocal

	if(l_loaded == GL_TRUE)
		return GL_TRUE;

	glGetStringLocal = GL_GetProcAddr("glGetString");
	glGetStringiLocal = GL_GetProcAddr("glGetStringi");
	glGetIntegervLocal = GL_GetProcAddr("glGetIntegerv");

	if(glGetStringLocal == NULL){
		LOG_ERROR("GL_LoadAPI: failed to retrieve 'glGetString' proc! Unable to load API.");
		return GL_FALSE;
	}

	version = glGetStringLocal(GL_VERSION);
	if(version == NULL){
		LOG_ERROR("GL_LoadAPI: failed to fetch GL version string! Maybe the context was not properly created.");
		return GL_FALSE;
	}

	if(sscanf(version, "%d.%d", &major, &minor) != 2){
		LOG_ERROR("GL_LoadAPI: invalid OpenGL version string! Maybe the context was not properly created.");
		return GL_FALSE;
	}

	// retrieving the implementation extensions
	// differs from OpenGL vesions prior to 3.0
	if(major < 3){
		l_extensionCount = 0;
		l_extensionString = glGetStringLocal(GL_EXTENSIONS);
		start = l_extensionString;
		while(*ptr != 0){
			if(*ptr == 0x20){
				*ptr = 0x00;
				l_pExtensions[l_extensionCount] = start;
				l_extensionCount++;
				start = ptr + 1;
			}
			ptr++;
		}
	}
	else{
		if(glGetIntegervLocal == NULL){
			LOG_ERROR("GL_LoadAPI: failed to retrieve 'glGetIntegerv' proc! Unable to load API.");
			return GL_FALSE;
		}

		if(glGetStringiLocal == NULL){
			LOG_ERROR("GL_LoadAPI: failed to retrieve 'glGetStringi' proc! Unable to load API.");
			return GL_FALSE;
		}

		glGetIntegervLocal(GL_NUM_EXTENSIONS, &l_extensionCount);
		for(i = 0; i < l_extensionCount; i++)
			l_pExtensions[i] = glGetStringi(GL_EXTENSIONS, i);
	}

	// Load GL Core
	//=================================================================
	#define GL_GET_PROC_ADDR(proc_type, proc_name)									\
		proc_name = (proc_type) GL_GetProcAddr(#proc_name);							\
		if(proc_name == NULL){														\
			LOG_ERROR("GL_LoadAPI: failed to load core proc '%s'!", #proc_name);	\
			res = GL_FALSE;															\
		}

	res = GL_TRUE;
''')

	for version, proc_list in GL_CORE_SORTED:
		f.write((r'''
	// OpenGL %.1f
	if(major < %d || major == %d && minor <= %d){
		res = GL_TRUE;

''' % (GL_VERSION.get(version, 0),
		GL_VERSION_MAJOR.get(version, 0),
		GL_VERSION_MAJOR.get(version, 0),
		GL_VERSION_MINOR.get(version, 0))).encode("utf-8"))

		for proc_type, proc_name in proc_list:
			f.write(("\t\tGL_GET_PROC_ADDR(%s, %s);\n" % (proc_type, proc_name)).encode("utf-8"))

		f.write((r'''
		if(res == GL_FALSE){
			LOG_ERROR("GL_LoadAPI: failed to load OpenGL Core %.1f!");
			return GL_FALSE;
		}
	}
''' % GL_VERSION.get(version, 0)).encode("utf-8"))

	f.write(br'''
	#undef GL_GET_PROC_ADDR
	//=================================================================

	// Load GL Extensions
	//=================================================================
''')

	# GL_EXTENSIONS

	f.write(br'''
	//=================================================================

	return GL_TRUE;
]

void GL_ReleaseAPI()
{
	GL_CloseLib();
	l_loaded = GL_FALSE;
}


''')
